### ISSUE TITLE
Change Heathrow end of Picadilly line to a loop

### ISSUE THREAD

**Issue by saxbophone** [quarbby/london-git#1]
Hey, cool project!

One improvement I've noticed which can be made is making the depiction of the Heathrow stations more accurate. The current version I can see in the graph shows them as one single line terminating at T5, when in fact the actual version contains two branches: one which goes to T5 and another unidirectional loop which goes via T4 to T123.

![Heathrow Terminal Stations](https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Piccadilly_T5_Extension.JPG/200px-Piccadilly_T5_Extension.JPG)

This sounds a bit tricky but I remember having a good idea on how to do it, so I may have a crack at it this weekend.

**Comment by saxbophone** [comment]
PS: Unclear what effect Pull Requests will have on the history of this project 😛  🤔 

If I get something working and am ready to push back to you, let me know how you want to proceed 👍

**Comment by quarbby** [comment]
Hey! Sorry for taking so long to reply; was away for a holiday. Sure thing, push anything that's working and we'll find a way! 
This repo will be a bit tricky on Pull Requests though 😄  But perhaps there's a workaround

**Comment by saxbophone** [comment]
No problem - wasn't that late of a reply 👍 

I'll probably fork this, then uh... fork the fork to use as a testing ground :)

**Comment by saxbophone** [comment]
it may be that you end up with two repos, one to track amendments to the actual script and preserve the source code history, and another as a 'showcase' to show the actual resulting tube graph, which gets overwritten on every update. That may be the easiest way of minimising the amount of headache caused, but at a slight cost of having two separate repos.

**Comment by quarbby** [comment]
That is true, but then I have to maintain two repos. Otherwise, i could just do with one repo, then do some screenshots/ gif or something. Yes, do fork it and try it out! Perhaps something interesting will come out of it!
